### PR TITLE
Fix handling of modified recurrences with lower sequence number than their base event

### PR DESCRIPTION
**Pull request by dstolpmann**
Hi,
the current implementation assumes that a modified recurrence has a higher sequence number than its base event. However, this is not always the case, as modifying the base event after creating a modified recurrence does only increase the sequence number of the base event.

This pull request fixes this behavior by also using the presents of the `sequence ID` field to determine if an event replaces another one. I am not sure if this behavior is according to the specification, but this topic seems to be highly controversial as stated in this article: https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/

Best regards,
dstolpmann

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Since you did the research, I am the more happy to merge this. 

With the assumption, you are right. I did not know how to handle this.

Thanks for adding an example and tests!
I wonder: The default case should already be accounted for in other places, I believe. So, there is no test necessary, right?

**Comment by niccokunzmann** [comment]
Following the release process in the README file, this change can be documented in the changelog. Would you like to create a PR for it, mentioning Issue and to your liking your username in a kind of consistent format with that what was noted down in the changelog before?

**Comment by dstolpmann** [comment]
Sure! Should I also increase the version number to v0.1.20b?

**Comment by niccokunzmann** [comment]
@dstolpmann yes!

**Pull request merged**
