### PR TITLE
Fix range with resource_ids. 

### PR DESCRIPTION
**Pull request by jabiertxof**
Fixes https://github.com/niccokunzmann/python-recurring-ical-events/issues/75

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, could you create a Pr against the issue-75 branch? that one has the tests in it that need passing.

Looking at che code, we cannot replace the core but somehow need to use one of the modifications when it is time.

**Comment by niccokunzmann** [comment]
Thanks! I merge it and check ...

**Comment by jabiertxof** [comment]
Hi Nicco, I'm  not familiar with github. Sorry for dont reply at time. Could you inform is my code is landed or erased (and why)? Thanks so much for your work.

**Comment by jabiertxof** [comment]
Hi Nicco.

If you not know, and as far I see, a event with recurrence-id with
"range" datetime must:

* Match a day with a recurrence and start at same time.  need to be
reseduled when original UID change DTSTART time or the rrrule skip the
overrided date.
* Think also the new recurrence created with the same UID need to start
at the day of the range datetime.
* Range changes is always for all events and couldent add "only to
mondays" for example because EVENTS with recurrence-id not have rrule.

This is to work OK not sure if spec define as it.

Thanks in advance for work on!

El lun, 09-09-2024 a las 12:19 -0700, Nicco Kunzmann escribió:
> Thanks! I merge it and check ...
> —
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you authored the thread.Message ID:
> <niccokunzmann/python-recurring-ical-
> ***@***.***>


[1] view it on GitHub
    https://github.com/niccokunzmann/python-recurring-ical-events/pull/171#issuecomment-2338897464
[2] unsubscribe

**Comment by niccokunzmann** [comment]
Hi, let's discuss this in the issue, so it is all together in one place.

**Pull request merged**
