### PR TITLE
Fixed crasher for repeated RRULE

### PR DESCRIPTION
**Pull request by spookylukey**
The ICS in the example was generated either by Fastmail or Thunderbird, or an interaction of the two, and causes a crasher like this:

```
  File ".../site-packages/recurring_ical_events.py", line 189, in __init__
    self.rrule = self.create_rule_with_start(_rule.to_ical().decode())
AttributeError: 'list' object has no attribute 'to_ical'
```

I'm assuming the correct fix is to do something like ignore all but the first, but I don't know.

Thanks!

### CODE REVIEW

**Comment by spookylukey** [comment]
According to https://www.kanzaki.com/docs/ical/rrule.html specifying multiple RRULE is valid.

So there are 2 things that really need to be done for a complete fix:

1) support multiple RRULEs
2) dedupe duplicate RRULEs

We could address the 2nd on its own i.e. dedupe, if the count after deduping 1 then we are fine, otherwise throw an assertion saying we don't support that yet.

**Comment by niccokunzmann** [comment]
All the rrules are added into one rule I think.

So, a new issue can be opened for that. The fix looks clean for now.

**Comment by niccokunzmann** [comment]
Would you like to follow the release process in the README?

**Comment by niccokunzmann** [comment]
Thanks for the fix!

**Comment by spookylukey** [comment]
> Would you like to follow the release process in the README?

I don't have write access for pushing/merging to the master branch, or any branches directly on this repo. I created a PR for the version bump but I can't merge it: https://github.com/niccokunzmann/python-recurring-ical-events/pull/105

**Comment by niccokunzmann** [comment]
@spookylukey Thanks again! This is deployed to PyPI as version 2.0.1

**Pull request merged**
