### PR TITLE
WIP: #48 Daylight aware repeats

### PR DESCRIPTION
**Pull request by niccokunzmann**
To solve the issue #48, this is created. You can create pull requests to the `issue-48` branch to contribute:

**Suggested implementation**

- [x] add an ICS file, example:
    https://github.com/niccokunzmann/python-recurring-ical-events/blob/f4a90b211f30bf0522f03514ba50eb69826f0fdb/test/calendars/issue-15-duplicated-events.ics#L1
- [ ] add a test, example:
    https://github.com/niccokunzmann/python-recurring-ical-events/blob/f4a90b211f30bf0522f03514ba50eb69826f0fdb/test/test_issue_15.py#L21
- [ ] implement the test
- [ ] fix the test

### CODE REVIEW

**Comment by ttmx** [comment]
Hey there! I'm trying to implement this, but am very new to pytest and date handling both. Any chance we could hop on discord or something? Thank you!

**Comment by niccokunzmann** [comment]
Hi,

I am sorry, this is quite hard for me, as I am far from the Internet, 
right now.

But, if you create a pull request with some code, I can comment - if it 
is running or not, does not matter.

**Comment by ttmx** [comment]
I've got the tests done, but digging through the code, the issue seemed to be on line 232 `for start in self.rule.between(span_start, span_stop, inc=True):`
Where it is seemingly not including the events when the self_start and self_stop are bound to daylight savings.
I know very little about how dates work in python, and I didn't want to have to dig through dateutil's code...
But I did.
I'm pretty sure the issue stems from the recurrence rule being set in a GMT+1 time of the year, and it is now GMT+0 time.
When the rule is checked, it does not "ignore" the daylight savings +1 or +0 part, so if I have had event at 10amGMT+1, it will now be checked against 10amGMT+1, instead of "just 10am", which means that when it is actually 10am in real life, the program will check the rule against 10amGMT+0, which will lead to this weird desynch.

Hope it made sense, I have no idea how to fix it 😎

Thank you!

**Comment by niccokunzmann** [comment]
Thanks cool. Canyou commit the tests and make a pull request? Then I can start with the code of the module.

**Comment by niccokunzmann** [comment]
Cool you found this. It is always hard to check these different types of dates and their compatibility with each other.

**Comment by niccokunzmann** [comment]
Here, we can see the tests: https://travis-ci.org/github/niccokunzmann/python-recurring-ical-events/branches Thanks @ttmx for the tests.

**Comment by niccokunzmann** [comment]
I found the mistake. It was not in the summertime change. Rrule.between works best witb days and that is what I added.

**Pull request merged**
