### PR TITLE
Tests for issue #48

### PR DESCRIPTION
**Pull request by iprak**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Wow. Thanks!

**Comment by niccokunzmann** [comment]
I think, these tests are fine for testing. Nice functions, clear purpose, readable code.


You could reduce their size to about 20 lines instead of 66 by using global variables and functions and pytest.parametrize - remove duplicated code through refactoring. That would be a huge contribution to the maintainance of the module.

I can merge it now or would you like to work on it before I merge it?
What do you think?

**Comment by iprak** [comment]
Thanks for the suggestion. I have not worked much with Python. The size is around 20 lines now.

**Comment by niccokunzmann** [comment]
Beautiful, thanks!

**Pull request merged**
